<?php

/**
 * Statik premium hekim sitesi — demo içerik.
 */
return [
    'unvan' => 'Uzm. Dr.',
    'ad_soyad' => 'Ayşe Yılmaz',
    'uzmanlik' => 'Dermatoloji & Estetik Tıp',
    'klinik_adi' => 'Yılmaz Dermatoloji Kliniği',
    'slogan' => 'Cildiniz, uzman ellerde güvenle yenilenir',
    'kisa_bio' => '15 yılı aşkın klinik deneyim, bilimsel protokollere dayalı tedavi ve kişiye özel estetik yaklaşımla Bursa’da premium dermatoloji hizmeti.',
    'bio' => 'Uzm. Dr. Ayşe Yılmaz, tıp eğitimini tamamladıktan sonra dermatoloji uzmanlığını yurt içi ve yurt dışı klinik stajlarla pekiştirmiştir. Tıbbi dermatoloji, lazer teknolojileri ve minimal invaziv estetik uygulamalarda binlerce danışana hizmet vermiştir. Kliniğimizde her tedavi planı; cilt tipi, yaşam tarzı ve beklentilerinize göre özelleştirilir.',
    'bio_uzun' => [
        'Hasta güvenliği ve şeffaf bilgilendirme, klinik pratiğimizin temelidir. Tedavi öncesi detaylı değerlendirme, dermoskopik inceleme ve gerekirse ileri görüntüleme yöntemleri ile doğru tanı konulur.',
        'Estetik uygulamalarda “doğal sonuç” felsefesini benimseriz. Abartısız, yüz anatomisine uyumlu ve yaşlanmaya dirençli planlar tercih edilir.',
        'Sürekli eğitim: Ulusal ve uluslararası kongreler, lazer protokolleri ve yeni nesil dolgu/botoks yaklaşımları düzenli takip edilir.',
    ],
    'telefon' => '0 (224) 555 00 00',
    'telefon_raw' => '+902245550000',
    'whatsapp' => '902245550000',
    'e_posta' => 'randevu@yilmazdermatoloji.com',
    'adres' => 'Örnek Mah. Sağlık Cad. No:12 Kat:3, Nilüfer / Bursa',
    'il' => 'Bursa',
    'ilce' => 'Nilüfer',
    'maps_embed' => 'https://maps.google.com/maps?q=Nil%C3%BCfer%20Bursa&t=&z=14&ie=UTF8&iwloc=&output=embed',
    'calisma_saatleri' => [
        'Pazartesi' => '09:00 – 18:30',
        'Salı' => '09:00 – 18:30',
        'Çarşamba' => '09:00 – 18:30',
        'Perşembe' => '09:00 – 18:30',
        'Cuma' => '09:00 – 18:30',
        'Cumartesi' => '09:00 – 14:00',
        'Pazar' => 'Kapalı',
    ],
    'sosyal' => [
        'instagram' => 'https://instagram.com',
        'facebook' => 'https://facebook.com',
        'youtube' => 'https://youtube.com',
        'linkedin' => 'https://linkedin.com',
    ],
    'istatistikler' => [
        ['deger' => 15, 'suffix' => '+', 'etiket' => 'Yıllık Deneyim', 'aciklama' => 'Klinik ve estetik pratik'],
        ['deger' => 8500, 'suffix' => '+', 'etiket' => 'Mutlu Danışan', 'aciklama' => 'Kişiye özel planlar'],
        ['deger' => 28, 'suffix' => '+', 'etiket' => 'Tedavi Protokolü', 'aciklama' => 'Kanıta dayalı uygulamalar'],
        ['deger' => 4.9, 'suffix' => '', 'etiket' => 'Ortalama Puan', 'aciklama' => 'Danışan değerlendirmeleri'],
    ],
    'slider' => [
        [
            'no' => '01',
            'baslik' => 'Cildiniz için premium klinik deneyim',
            'alt' => 'Steril ortam, uzman hekim ve modern cihazlarla kişiye özel dermatoloji planı.',
            'cta' => 'Online Randevu',
            'cta_url' => '/randevu',
            'cta2' => 'Kliniği Keşfet',
            'cta2_url' => '/galeri',
            'image' => '/images/placeholder.svg',
            'thumb' => '/images/placeholder.svg',
            'badge' => 'Bursa · Nilüfer',
            'etiket' => 'Klinik',
            'meta' => ['15+ yıl deneyim', 'Steril protokol', 'Aynı gün dönüş'],
        ],
        [
            'no' => '02',
            'baslik' => 'Doğal estetik, abartısız sonuçlar',
            'alt' => 'Botoks, dolgu ve cilt yenilemede yüz anatomisine saygılı, dengeli planlama.',
            'cta' => 'Estetik Hizmetler',
            'cta_url' => '/hizmetler',
            'cta2' => 'Öncesi / Sonrası',
            'cta2_url' => '/galeri',
            'image' => '/images/placeholder.svg',
            'thumb' => '/images/placeholder.svg',
            'badge' => 'Minimal İnvaziv',
            'etiket' => 'Estetik',
            'meta' => ['Doğal görünüm', 'Kayıtlı ürünler', 'Yazılı onam'],
        ],
        [
            'no' => '03',
            'baslik' => 'Lazer teknolojisiyle hassas tedavi',
            'alt' => 'Leke, damar, epilasyon ve skar yönetiminde güvenli, parametre odaklı seanslar.',
            'cta' => 'Lazer Tedavileri',
            'cta_url' => '/hizmetler',
            'cta2' => 'Sık Sorulanlar',
            'cta2_url' => '/sss',
            'image' => '/images/placeholder.svg',
            'thumb' => '/images/placeholder.svg',
            'badge' => 'Teknoloji',
            'etiket' => 'Lazer',
            'meta' => ['Cilt tipi analizi', 'Seans planı', 'Güneş koruma rehberi'],
        ],
        [
            'no' => '04',
            'baslik' => 'Erken tanı için dermoskopik takip',
            'alt' => 'Ben haritalama, risk değerlendirmesi ve düzenli kontrol ile huzurlu takip süreci.',
            'cta' => 'Randevu Al',
            'cta_url' => '/randevu',
            'cta2' => 'Hakkımda',
            'cta2_url' => '/hakkimda',
            'image' => '/images/placeholder.svg',
            'thumb' => '/images/placeholder.svg',
            'badge' => 'Önleyici Tıp',
            'etiket' => 'Takip',
            'meta' => ['Dijital arşiv', 'Risk skoru', 'Hasta eğitimi'],
        ],
    ],
    'hizmetler' => [
        [
            'baslik' => 'Genel Dermatoloji',
            'kisa' => 'Akne, egzama, sedef ve cilt enfeksiyonlarında tanı + tedavi.',
            'aciklama' => 'Kapsamlı cilt muayenesi, laboratuvar ve dermoskopi ile doğru tanı. Akut ve kronik dermatolojik hastalıklarda güncel ilaç protokolleri.',
            'sure' => '30–45 dk',
            'fiyat' => 'Muayene ücreti klinik politikasına göre',
            'renk' => 'teal',
            'image' => '/images/placeholder.svg',
            'madde' => ['Akne & rozasea', 'Egzama & sedef', 'Mantar enfeksiyonları', 'Saç dökülmesi değerlendirmesi'],
        ],
        [
            'baslik' => 'Estetik Uygulamalar',
            'kisa' => 'Botoks, dolgu, mezoterapi ve cilt kalitesi protokolleri.',
            'aciklama' => 'Yüz analizi sonrası doğal görünüm hedefli enjeksiyon planları. Hijyenik, kayıtlı ürün ve şeffaf bilgilendirme.',
            'sure' => '20–40 dk',
            'fiyat' => 'Uygulama alanına göre değişir',
            'renk' => 'gold',
            'image' => '/images/placeholder.svg',
            'madde' => ['Botulinum toksin', 'Hyaluronik dolgu', 'Mezoterapi', 'PRP destekli protokoller'],
        ],
        [
            'baslik' => 'Lazer Tedavileri',
            'kisa' => 'Leke, damar, epilasyon ve skar yönetiminde lazer.',
            'aciklama' => 'Cilt tipine uygun parametrelerle planlanan lazer seansları. Seans aralıkları ve bakım önerileri yazılı verilir.',
            'sure' => '15–60 dk',
            'fiyat' => 'Seans paketleri mevcut',
            'renk' => 'violet',
            'image' => '/images/placeholder.svg',
            'madde' => ['Leke & pigmentasyon', 'Damar lezyonları', 'Lazer epilasyon', 'Yara izi / akne skarı'],
        ],
        [
            'baslik' => 'Ben Takibi & Dermoskopi',
            'kisa' => 'Erken tanı odaklı haritalama ve takip.',
            'aciklama' => 'Şüpheli lezyonların dijital dermoskopik kaydı, risk skorlaması ve gerektiğinde biyopsi yönlendirmesi.',
            'sure' => '30–50 dk',
            'fiyat' => 'Kontrol paketleri',
            'renk' => 'rose',
            'image' => '/images/placeholder.svg',
            'madde' => ['Total vücut muayenesi', 'Dijital dermoskopi', 'Risk takibi', 'Hasta eğitimi'],
        ],
        [
            'baslik' => 'Cilt Bakım Programları',
            'kisa' => 'Medikal peels, hidrafacial ve bakım protokolleri.',
            'aciklama' => 'Sezonluk cilt ihtiyaçlarına göre bakım programları. Ev bakım ürün önerileri hekim onaylıdır.',
            'sure' => '45–60 dk',
            'fiyat' => 'Paket avantajları',
            'renk' => 'sky',
            'image' => '/images/placeholder.svg',
            'madde' => ['Kimyasal peeling', 'Cilt yenileme', 'Nem & bariyer onarımı', 'Ev bakım planı'],
        ],
        [
            'baslik' => 'Online / Kontrol Muayenesi',
            'kisa' => 'Takip randevuları ve tedavi değerlendirmesi.',
            'aciklama' => 'Tedavi yanıtı, yan etki yönetimi ve plan güncellemesi için kısa kontroller.',
            'sure' => '15–20 dk',
            'fiyat' => 'Kontrol tarifesi',
            'renk' => 'slate',
            'image' => '/images/placeholder.svg',
            'madde' => ['Tedavi takibi', 'Fotoğraf karşılaştırması', 'Plan revizyonu', 'Ürün danışmanlığı'],
        ],
    ],
    'surec' => [
        ['adim' => '01', 'baslik' => 'Randevu', 'aciklama' => 'Online form veya telefon ile uygun günü seçin.'],
        ['adim' => '02', 'baslik' => 'Değerlendirme', 'aciklama' => 'Detaylı anamnez, muayene ve gerekirse dermoskopi.'],
        ['adim' => '03', 'baslik' => 'Plan', 'aciklama' => 'Size özel tedavi ve bakım planı netleştirilir.'],
        ['adim' => '04', 'baslik' => 'Takip', 'aciklama' => 'Sonuçlar kontrol randevularıyla izlenir.'],
    ],
    'galeri' => [
        ['baslik' => 'Resepsiyon', 'etiket' => 'Klinik', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'Muayene Odası', 'etiket' => 'Klinik', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'Lazer Ünitesi', 'etiket' => 'Teknoloji', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'Bekleme Salonu', 'etiket' => 'Konfor', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'Sterilizasyon', 'etiket' => 'Güvenlik', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'Konsültasyon', 'etiket' => 'Danışmanlık', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'Cihaz Parkı', 'etiket' => 'Teknoloji', 'image' => '/images/placeholder.svg'],
        ['baslik' => 'VIP Oda', 'etiket' => 'Konfor', 'image' => '/images/placeholder.svg'],
    ],
    'oncesi_sonrasi' => [
        [
            'baslik' => 'Akne skar iyileşmesi',
            'sure' => '4 seans protokol',
            'before' => '/images/placeholder.svg',
            'after' => '/images/placeholder.svg',
        ],
        [
            'baslik' => 'Leke tedavisi',
            'sure' => '3 seans lazer',
            'before' => '/images/placeholder.svg',
            'after' => '/images/placeholder.svg',
        ],
    ],
    'yorumlar' => [
        [
            'ad' => 'Elif K.',
            'metin' => 'Yıllardır akne izleriyle uğraşıyordum. Plan net anlatıldı, seanslar düzenli ilerledi. Sonuçlar beklentimin üzerinde.',
            'puan' => 5,
            'hizmet' => 'Akne skarı',
        ],
        [
            'ad' => 'Merve T.',
            'metin' => 'Botoks uygulaması çok doğal oldu. Kimse fark etmedi ama yorgun ifadem gitti. Klinik hijyen ve ilgi harika.',
            'puan' => 5,
            'hizmet' => 'Estetik',
        ],
        [
            'ad' => 'Selin A.',
            'metin' => 'Leke tedavisi sürecinde her adım fotoğraflarla takip edildi. Bilgilendirme çok şeffaf.',
            'puan' => 5,
            'hizmet' => 'Lazer',
        ],
        [
            'ad' => 'Deniz Y.',
            'metin' => 'Ben takibinde detaylı dermoskopi yapıldı. Endişelerim giderildi, kontrol randevusu planlandı.',
            'puan' => 5,
            'hizmet' => 'Dermoskopi',
        ],
        [
            'ad' => 'Ayça B.',
            'metin' => 'Randevu süreci kolay, klinik ferah. Dr. Yılmaz çok dinliyor ve acele etmiyor.',
            'puan' => 5,
            'hizmet' => 'Muayene',
        ],
    ],
    'ekip' => [
        [
            'ad' => 'Uzm. Dr. Ayşe Yılmaz',
            'rol' => 'Dermatoloji Uzmanı · Kurucu',
            'image' => '/images/placeholder.svg',
        ],
        [
            'ad' => 'Hemşire Zeynep A.',
            'rol' => 'Klinik Koordinatör',
            'image' => '/images/placeholder.svg',
        ],
        [
            'ad' => 'Estetisyen Merve S.',
            'rol' => 'Medikal Cilt Bakımı',
            'image' => '/images/placeholder.svg',
        ],
    ],
    'egitim' => [
        ['yil' => '2005', 'baslik' => 'Tıp Fakültesi Mezuniyeti', 'aciklama' => 'Tıp doktorluğu eğitimini onur derecesiyle tamamladı.'],
        ['yil' => '2011', 'baslik' => 'Dermatoloji Uzmanlığı', 'aciklama' => 'Uzmanlık eğitimi ve klinik rotasyonlar.'],
        ['yil' => '2015', 'baslik' => 'Lazer & Estetik Sertifikaları', 'aciklama' => 'Uluslararası lazer ve enjeksiyon eğitimleri.'],
        ['yil' => '2019', 'baslik' => 'Klinik Kuruluşu', 'aciklama' => 'Nilüfer’de modern dermatoloji kliniği açıldı.'],
        ['yil' => '2024', 'baslik' => 'Dijital Randevu Entegrasyonu', 'aciklama' => 'Randevu Ajandam altyapısı ile online randevu.'],
    ],
    'bloglar' => [
        [
            'slug' => 'yaz-aylarinda-gunes-korumasi',
            'baslik' => 'Yaz Aylarında Güneş Koruması: SPF Seçim Rehberi',
            'ozet' => 'SPF, PA, uygulama sıklığı ve cilt tipine göre doğru güneş koruyucu nasıl seçilir?',
            'tarih' => '12 Haziran 2026',
            'okuma' => '6 dk',
            'kategori' => 'Cilt Sağlığı',
            'image' => '/images/placeholder.svg',
            'icerik' => [
                'Güneş koruyucu yalnızca plajda değil, günlük şehir hayatında da cilt yaşlanması ve leke oluşumunu yavaşlatan en etkili araçtır.',
                'SPF 30 ve üzeri, geniş spektrum (UVA+UVB) ürünler tercih edilmelidir. Yağlı ciltlerde jel/fluid formlar; kuru ciltlerde krem formlar daha konforludur.',
                'Uygulama: Yüze yaklaşık 1 çay kaşığı kadar ürün, dışarı çıkmadan 15–20 dakika önce sürülmeli; her 2–3 saatte yenilenmelidir.',
            ],
        ],
        [
            'slug' => 'akne-tedavisinde-yeni-yaklasimlar',
            'baslik' => 'Akne Tedavisinde Güncel Yaklaşımlar',
            'ozet' => 'Hafif ve orta şiddette aknede basamaklı tedavi, bakım ve skar önleme.',
            'tarih' => '28 Mayıs 2026',
            'okuma' => '8 dk',
            'kategori' => 'Tedavi',
            'image' => '/images/placeholder.svg',
            'icerik' => [
                'Akne; hormonal, mikrobiyal ve inflamatuar bileşenleri olan multifaktöriyel bir hastalıktır. “Tek ürün mucizesi” yerine kişiye özel basamaklı plan gerekir.',
                'Topikal retinoidler, benzoil peroksit ve gerektiğinde sistemik tedaviler hekim kontrolünde planlanır.',
                'Skar oluşmadan inflamasyonu kontrol etmek, uzun vadede en iyi estetik sonucu sağlar.',
            ],
        ],
        [
            'slug' => 'botoks-hakkinda-bilinmesi-gerekenler',
            'baslik' => 'Botoks Hakkında Bilmeniz Gereken 7 Şey',
            'ozet' => 'Kimlere uygulanır, etki süresi, doğal sonuç için kritik noktalar.',
            'tarih' => '10 Mayıs 2026',
            'okuma' => '5 dk',
            'kategori' => 'Estetik',
            'image' => '/images/placeholder.svg',
            'icerik' => [
                'Botulinum toksin, dinamik kırışıklıklarda kas aktivitesini geçici olarak azaltır. Doğru doz ve nokta seçimi doğal ifade için kritiktir.',
                'Etki genellikle 3–7 günde başlar, 3–4 ay sürer. Hamilelik, emzirme ve bazı nöromüsküler hastalıklarda uygulanmaz.',
                'İyi bir botoks “yapıldığı belli olmayan” botokstur.',
            ],
        ],
        [
            'slug' => 'kislik-cilt-bakim-rutini',
            'baslik' => 'Kışın Cilt Bariyerini Güçlendiren Rutin',
            'ozet' => 'Soğuk hava ve kalorifer kuruluğuna karşı nem ve bariyer stratejisi.',
            'tarih' => '18 Nisan 2026',
            'okuma' => '4 dk',
            'kategori' => 'Bakım',
            'image' => '/images/placeholder.svg',
            'icerik' => [
                'Kışın cilt bariyeri zayıflar; kaşıntı, pullanma ve hassasiyet artabilir. Nazik temizleyici + seramidli nemlendirici temeldir.',
                'Aktif asit kullanımını hekim önerisi olmadan artırmayın. Güneş koruyucu kışın da ihmal edilmemelidir.',
            ],
        ],
    ],
    'sss' => [
        [
            'soru' => 'Randevu nasıl alabilirim?',
            'cevap' => 'Web sitemizdeki randevu formunu doldurabilir, telefon veya WhatsApp hattımızı arayabilirsiniz. Uygun slot onaylandıktan sonra size bilgilendirme yapılır.',
        ],
        [
            'soru' => 'İlk muayenede neler yapılır?',
            'cevap' => 'Detaylı anamnez, cilt muayenesi ve gerektiğinde dermoskopi uygulanır. Size özel tedavi planı ve tahmini seans sayısı paylaşılır.',
        ],
        [
            'soru' => 'Lazer sonrası iyileşme süreci nasıldır?',
            'cevap' => 'Uygulama tipine göre 24–72 saat hafif kızarıklık normaldir. Güneş koruması ve hekim önerisi ürünler kullanılmalıdır. Detaylar seans sonrası yazılı verilir.',
        ],
        [
            'soru' => 'Botoks / dolgu sonrası işe dönebilir miyim?',
            'cevap' => 'Çoğu danışan aynı gün sosyal hayatına döner. Yoğun egzersiz, sauna ve yüzüstü uyku ilk 24 saatte önerilmez.',
        ],
        [
            'soru' => 'Randevumu iptal edebilir miyim?',
            'cevap' => 'Evet. Randevu saatinden en az 24 saat önce haber vermeniz, diğer danışanlara slot açmamızı sağlar.',
        ],
        [
            'soru' => 'Sigorta ile anlaşmalı mısınız?',
            'cevap' => 'Anlaşmalı kurum listesi dönemsel güncellenir. Güncel bilgi için resepsiyonu arayabilirsiniz. Estetik işlemler genelde özel ücretlidir.',
        ],
        [
            'soru' => 'Hangi yaş gruplarına bakıyorsunuz?',
            'cevap' => 'Ergenlik aknesinden yetişkin leke ve yaşlanma tedavisine kadar geniş bir yelpazede hizmet veriyoruz. Çocuk dermatolojisi için ayrı yönlendirme yapılabilir.',
        ],
        [
            'soru' => 'Klinik hijyen standartları nelerdir?',
            'cevap' => 'Tek kullanımlık malzemeler, cihaz sterilizasyon protokolleri ve oda dezenfeksiyonu düzenli uygulanır. Enjeksiyon ürünleri orijinal ve izlenebilir lot numaralıdır.',
        ],
    ],
    'ozellikler' => [
        ['baslik' => 'Steril Klinik', 'aciklama' => 'Uluslararası hijyen protokolleri'],
        ['baslik' => 'Kayıtlı Ürünler', 'aciklama' => 'İzlenebilir lot ve orijinal ampuller'],
        ['baslik' => 'Dijital Takip', 'aciklama' => 'Fotoğraf & tedavi arşivi'],
        ['baslik' => 'Şeffaf Plan', 'aciklama' => 'Yazılı bilgilendirme ve onam'],
    ],
    'partnerler' => ['Allergan', 'Galderma', 'Candela', 'Cynosure', 'La Roche-Posay', 'CeraVe'],
];
